### ISSUE TITLE
Portuguese PT-BR Localization

### ISSUE THREAD

**Issue by clustermage** [JPLRepo/JSIAdvTransparentPods#35]
Localization
{
	pt-br
	{
		#autoLOC_JISATP_00001	= LIGA
		#autoLOC_JISATP_00002	= DESLIGA
		#autoLOC_JISATP_00003	= AUTOMÁTICO
		#autoLOC_JISATP_00004	= As janelas desta cápsula tiveram uma limpeza avançada.
		#autoLOC_JISATP_00005	= Pod Transparente
		#autoLOC_JISATP_00006	= JSI Opções Avançadas Módulos Transparentes
		#autoLOC_JISATP_00007	= JSI Pods Transparentes Avançados
		#autoLOC_JISATP_00008	= Registros de Depuração Extra
		#autoLOC_JISATP_00009	= Ative para capturar muitas informações extras no log do KSP para relatar um problema.
		#autoLOC_JISATP_00010	= As embarcações carregadas possuem Módulos Transparentes.
		#autoLOC_JISATP_00011	= Ative para ter Módulos Transparentes em todos as embarcações carregadas (além da embarcação ativa), se Desligado, apenas a Embarcação Ativa será transparente.
	}
}

**Comment by JPLRepo** [comment]
Thanks very much. Will be included in next version when KSP 1.9 comes out.
