### ISSUE TITLE
NREs with JSI ATP, OSE Workshop and EPL module on the same part

### ISSUE THREAD

**Issue by EleusisLaArwall** [JPLRepo/JSIAdvTransparentPods#9]
**KSP:** 1.1.2.1260 (win64) clean install; fresh sandbox

**Problem:** NREs with JSI ATP, OSE and EL module on the same part

**Mods installed:** (used latest versions available for KSP 1.1.2)
Module Manager 2.6.25
JSI Advanced Transparent Pods 0.1.6.0
Kerbal Inventory System 1.2.11 and 1.2.12 (only one at a time of course)
OSE Workshop 0.14.0
Extraplanetary Launchpads 5.3.2 (does not need to be installed to cause NRE)
Endurance (from Interstellar) Continued 1.1 (modified as described below)

**Changes:** (in GameData\Endurance\Parts\Ranger\ranger.cfg - line 255-267)
```
	MODULE
	{
		name = ExWorkshop
		ProductivityFactor = 5
	}		
	MODULE
	{
		name = OseModuleWorkshop
		ProductivityFactor = 0.25
		UpkeepResource = ElectricCharge
		MinimumCrew = 1
		Animate = false
	}
```

**Reproduction steps:**
Just pick up the ranger in the VAB and NREs start. 
If JSI Advanced Transparent Pods **or** Kerbal Inventory System **or** OSE Workshop is removed from the mod-list the NREs will no longer pop-up. It doesn't matter if EL is installed or not as long as the `ExWorkshop` module is configured. Without `ExWorkshop` module the NREs don't show up.
Other EL modules like `ExSurveyStation` seem to result in the same NREs.
If the `OseModuleWorkshop` module is removed the NREs stop.

**Log:** [http://s000.tinyupload.com/?file_id=89997290356445921367](http://s000.tinyupload.com/?file_id=89997290356445921367)
(NREs start at line 17592)

**Notes:** I noticed these NREs with my own parts and to make sure that I haven't mis-configured them I tried to reproduce it with the Endurance mod in a fresh environment.
I'm not 100% sure that this is the right place to post because OSE seems to produce the first NRE but the majority involves `... JSIAdvTransparentPods ...`.

**Comment by JPLRepo** [comment]
Sorry I cannot open you log file without signing up to that site. Which I won't.
Also, this is all on 1.1.2? Sugest you upgrade and try again. Otherwise this goes very low on my care o' meter.

**Comment by EleusisLaArwall** [comment]
Thanks for the fast reply. Can't reproduce it in KSP 1.1.3 at all. Sorry that I wasted your time on this.
